name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Biome
        uses: biomejs/setup-biome@v2

      - name: 🔍 Code check
        run: biome ci

  build:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: bun ci

      - name: 🔍 Type Check
        run: bun check:types
