name: convex

on:
  push:
    branches:
      - main
    paths:
      - "packages/server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/server
    environment: deploy-convex
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: 🔑 Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: 🔄 Sync environment variables to Convex
        run: |
          doppler secrets download --no-file --format env-no-quotes | \
          while IFS='=' read -r key value; do
            bunx convex env set "$key" "$value"
          done

      - name: 🚀 Deploy Convex
        run: bunx convex deploy
