name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: deploy
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install Vercel CLI
        run: bun add --global vercel@latest

      - name: 🚀 Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd apps/web
