name: scraper

on:
  push:
    branches:
      - main
    paths:
      - "apps/scraper/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-scraper

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: 🚀 Deploy to Cloudflare Workers
        run: cd ./apps/scraper && bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
